### ISSUE TITLE
Need some help getting the tftp page working properly with the latest version. 

### ISSUE THREAD

**Issue by prophit40** [Cynjut/SCCP_Manager#2]
Was wondering if you were able to support me on getting this last issue resolved? I can upload my current file set. I was able to get everything working but the tftp page. it loads the page with the data from xmldefaults. When I hit submit I get error, file_get_contents(): Filename cannot be empty 
1.    $filename = "/tftpboot/$tftpdisplay.cnf.xml";
2.    $tftpfile = file_get_contents($inputfile);
   802.//
   803.// I know this look crazy, but we pull the "<Default>" tags from the
   error is on line 801. 

Let me know if you are able to help and what you need from me. Thanks

**Comment by Cynjut** [comment]
Just double-checked. This should be working in 1.1.2
